### PR TITLE
Utility: remove unused utility class

### PR DESCRIPTION
**Pull request by aarani**
BigIntegerSerialization was unused so let's
remove it.

### CODE REVIEW

**Comment by knocte** [comment]
@aarani what's left to do here?

**Comment by aarani** [comment]
> @aarani what's left to do here?

The PR title is misleading because I never actually did "refactor Utility namespace". There's currently only one commit that removes an unused file.

**Comment by knocte** [comment]
So?

**Comment by aarani** [comment]
> So?

Since I don't want to refactor Utility namespace for now, I synced the PR title with the only commit msg it had.

**Review by knocte — APPROVED** [review]

**Pull request merged**
