### PR TITLE
TorLogger: prevent double initialization

### PR DESCRIPTION
**Pull request by knocte**

### CODE REVIEW

**Comment by knocte** [comment]
@aarani haha this breaks tests; can you finish the PR please?

**Comment by knocte** [comment]
@aarani why is CI still red?

**Comment by knocte** [comment]
@aarani the rename commit has disappeared 😭

**Comment by aarani** [comment]
> > @aarani the rename commit has disappeared 😭
> 
> No clue what is happening the branch has that commit but PR doesn't

I repushed 1 by 1 it seems to be back

**Pull request merged**
