### PR TITLE
Services: use typed exn for service introduction

### PR DESCRIPTION
**Pull request by aarani**
This commit changes the generic exception (happening after failed introduction attempt) to a typed exception so it can be easily caught and handled.

### CODE REVIEW

**Comment by knocte** [comment]
@aarani with this change, you're losing ack.Status info. Why was it unsuccessful?

**Comment by aarani** [comment]
> with this change, you're losing ack.Status info. Why was it unsuccessful?

The reason I removed it was because RelayIntroduceStatus is not accessible from Exceptions.fs (it's at the top of the codbase), I can log it though 🤔

**Comment by knocte** [comment]
> The reason I removed it was because RelayIntroduceStatus is not accessible from Exceptions.fs 

Why not?

**Comment by aarani** [comment]
> Why not?

RelayIntroduceStatus is defined in the Cells namespace which is lower than Exceptions.fs

**Comment by knocte** [comment]
> RelayIntroduceStatus is defined in the Cells namespace which is lower than Exceptions.fs

This sounds like something that can be fixed.

**Comment by aarani** [comment]
> > RelayIntroduceStatus is defined in the Cells namespace which is lower than Exceptions.fs
> 
> This sounds like something that can be fixed.

Fixed 🤔

**Review by knocte — APPROVED** [review]

**Pull request merged**
